// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Food = __t.object("Food", {
  id: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  color: __t.string(),
});
export type Food = __Infer<typeof Food>;

export const GameTick = __t.object("GameTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTick = __Infer<typeof GameTick>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.string(),
  score: __t.u32(),
  length: __t.u32(),
  direction: __t.u8(),
  alive: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  pendingDirection: __t.u8(),
});
export type Player = __Infer<typeof Player>;

export const PlayerDiedEvent = __t.object("PlayerDiedEvent", {
  identity: __t.identity(),
  killerName: __t.string(),
});
export type PlayerDiedEvent = __Infer<typeof PlayerDiedEvent>;

export const PlayerJoinedEvent = __t.object("PlayerJoinedEvent", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
});
export type PlayerJoinedEvent = __Infer<typeof PlayerJoinedEvent>;

export const PlayerPositionEvent = __t.object("PlayerPositionEvent", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  direction: __t.u8(),
});
export type PlayerPositionEvent = __Infer<typeof PlayerPositionEvent>;

export const SnakeSegment = __t.object("SnakeSegment", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  segmentIndex: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
});
export type SnakeSegment = __Infer<typeof SnakeSegment>;

